### ISSUE TITLE
can not find Yuneec-SDK-Android

### ISSUE THREAD

**Issue by yaosheng79** [YUNEEC/Yuneec-SDK-Android-Example#50]
seems like this repo dose not exist any more.
where can I find the android sdk required to build this example project?

**Comment by julianoes** [comment]
You could give https://mavsdk.mavlink.io/ a try. There is work in progress for Android: https://github.com/mavlink/MAVSDK-Java/

**Comment by benoit12** [comment]
@julianoes I have the same Issue, it seems that the jitpack for Yuneec is not maintained anymore.
I have a lot of difficulties to reach Yuneec support for development and can't create a Dev account on their site (Captcha error). You are suggesting to use Mavlink for Yuneec development, is that the new way to develop with Yuneec drone (ex H520)? For instance, we can develop with mavlink/MAVSDK-CSharp and we'll have full control over the drone (I guess it uses a mavlink compatible controller)?

**Comment by julianoes** [comment]
As far as I know the Yuneec SDK is no longer maintained.

Therefore, I would recommend to use MAVSDK but I can't guarantee that everything will work perfectly because there might have been changes in the meantime that I am not aware of.

I would expect the following to work:
- missions with camera and gimbal actions
- gimbal control
- camera control (for ET10 not sure)
- offboard with GPS (but probably not for indoor / GPS denied)

FYI: @darioxz.

**Comment by darioxz** [comment]
Correct. Yuneec currently only offers limited support for their SDK. Full support for MAVSDK is in the works and will be announced once officially available.

@benoit12 The required binaries (previously hosted on Jitpack) can be downloaded here:
Release: https://7a385c3b-88a9-2913-f590-6eecf3be1731.s3.eu-central-1.amazonaws.com/yuneec-sdk/android/DroneCore-Android-v0.14.5-Release.zip  
Debug: https://7a385c3b-88a9-2913-f590-6eecf3be1731.s3.eu-central-1.amazonaws.com/yuneec-sdk/android/DroneCore-Android-v0.14.5-Debug.zip
